import IUser from '../../models/IUser';

export const Users: IUser[] =[
  {
    id: "1",
    displayName: "John Doe",
    mail: "john.doe@domain.com",
    mobilePhone: "+1 5550001111",
    jobTitle: "HR Manager",
    officeLocation: "Atlanta East Side",
    department: "Human Resources",
    companyName: "Solutions",
    city: "Atlanta, GA",
    country: "US",
    userPrincipalName: "john.doe@domain.com",
    imageUrl: `https://randomuser.me/api/portraits/men/${Math.floor(Math.random() * 50) + 1}.jpg`,
  },
  {
    id: "2",
    displayName: "Ben Williams",
    mail: "ben.williams@domain.com",
    mobilePhone: "+1 5551112222",
    jobTitle: "Operations Chief",
    officeLocation: "Dallas North Side",
    department: "Operations",
    companyName: "Solutions",
    city: "Dallas, TX",
    country: "US",
    userPrincipalName: "ben.williams@domain.com",
  },
  {
    id: "3",
    displayName: "Mary Jane",
    mail: "mary.jane@domain.com",
    mobilePhone: "+1 5552223333",
    jobTitle: "Sales Representative",
    officeLocation: "San Francisco South Side",
    department: "Sales",
    companyName: "Solutions",
    city: "San Francisco, CA",
    country: "US",
    userPrincipalName: "mary.jane@domain.com",
    imageUrl: `https://randomuser.me/api/portraits/women/${Math.floor(Math.random() * 50) + 1}.jpg`,
  },
  {
    id: "4",
    displayName: "Laura Rogers",
    mail: "laura.rogers@domain.com",
    mobilePhone: "+1 5553334444",
    jobTitle: "Finance Director",
    officeLocation: "Chelsea",
    department: "Finance",
    companyName: "Solutions",
    city: "New York, NY",
    country: "US",
    userPrincipalName: "laura.rogers@domain.com",
  },
  {
    id: "5",
    displayName: "Claudia Perez",
    mail: "claudia.perez@domain.com",
    mobilePhone: "+52 8881110000",
    jobTitle: "IT Director",
    officeLocation: "Monterrey Sur",
    department: "Information Technologies",
    companyName: "Solutions",
    city: "Monterrey, NL",
    country: "MX",
    userPrincipalName: "claudia.perez@domain.com",
    imageUrl: `https://randomuser.me/api/portraits/women/${Math.floor(Math.random() * 50) + 1}.jpg`,
  },
  {
    id: "6",
    displayName: "Noah Ross",
    mail: "noah.ross@domain.com",
    mobilePhone: "+52 9991110000",
    jobTitle: "Customer Service Senior",
    officeLocation: "Central Business District",
    department: "Customer Service",
    companyName: "Solutions",
    city: "London, UK",
    country: "UK",
    userPrincipalName: "noah.ross@domain.com",
    imageUrl: `https://randomuser.me/api/portraits/men/${Math.floor(Math.random() * 50) + 1}.jpg`,
  }
];